name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  pre-commit:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["ubuntu-22.04", "macos-12", "windows-2019"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Run lint
        uses: ./.github/actions/lint
  tests:
    needs: pre-commit
    strategy:
      matrix:
        python-version: ["3.10"]
        os: ["ubuntu-22.04", "macos-12", "windows-2019"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        uses: ./.github/actions/test
        with:
          disk_cache: test-${{ matrix.os }}-${{ matrix.python-version }}
  benchmarks:
    needs: tests
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run benchmarks
        uses: ./.github/actions/benchmarks
        with:
          disk_cache: benchmark-${{ matrix.os }}
