name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  torch_examples:
    strategy:
      matrix:
        python-version: ["3.10"]
        os: ["ubuntu-22.04"]
    runs-on: ${{ matrix.os }}
    env:
      HOROVOD_WITH_GLOO: 1
      HOROVOD_WITHOUT_MPI: 1
      HOROVOD_WITHOUT_TENSORFLOW: 1
      HOROVOD_WITH_PYTORCH: 1
      HOROVOD_WITHOUT_MXNET: 1
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install torch
        run: pip install --timeout 300 torch==1.13.1 && HOROVOD_WITH_PYTORCH=1 pip install --timeout 300 --no-cache-dir horovod[torch]==0.25.0
      - name: Uninstall cached deepgnn packages
        run: pip uninstall deepgnn-ge deepgnn-torch
      - name: Install wheels
        run: pip install deepgnn_ge*.whl deepgnn_torch*.whl
      - name: Run gat examples
        run: cd ./pytorch/gat/ && sudo chmod +x *.sh && bash ./run.sh CPU
      - name: Run pytorch geometric examples
        run: cd ./pytorch/geometric/gat/ && sudo chmod +x *.sh && bash ./run.sh CPU
      - name: Run graphsage supervised examples
        run: cd ./pytorch/graphsage/ && sudo chmod +x *.sh && bash ./run.sh supervised no CPU && bash ./run.sh supervised no CPU disk yes
      - name: Run graphsage unsupervised examples
        run: cd ./pytorch/graphsage/ && sudo chmod +x *.sh && bash ./run.sh unsupervised no CPU
      - name: Run hetgnn examples
        run: cd ./pytorch/hetgnn/ && sudo chmod +x *.sh && bash ./run.sh CPU
